# Generated by Django 5.0.6 on 2024-07-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0002_alter_short_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='short',
            old_name='Date',
            new_name='postDate',
        ),
    ]
