# Generated by Django 5.0.6 on 2024-07-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
