# Generated by Django 5.0.6 on 2024-07-03 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
        ('short', '0003_rename_date_short_postdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='series.series'),
            preserve_default=False,
        ),
    ]
