# Generated by Django 5.0.6 on 2024-07-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_article_series'),
        ('series', '0001_initial'),
        ('short', '0004_short_series'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
