# Generated by Django 5.0.6 on 2024-07-03 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_remove_article_timestamp_article_postdate'),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='series.series'),
            preserve_default=False,
        ),
    ]
